site_name: DKsec
site_url: https://sitename.example
theme:
  name: material
  palette:
    scheme: slate
nav:
  - Home: index.md
  - TCS_HackQuest:
      - TCS_HackQuest_Round_1: TCS_HackQuest/TCS_HackQuest_Round1.md
      - TCS_HackQuest_Round_2: TCS_HackQuest/TCS_HackQuest_Round2.md
  - PortSwigger Web-Security Labs:
      - Authentication: Portswigger_labs/Authentication.md
      - Business logic vulnerabilities: Portswigger_labs/Business_logic_vulnerabilities.md
      - Clickjacking: Portswigger_labs/Clickjacking.md
      - Cross-origin resource sharing (CORS): Portswigger_labs/CORS.md
      - Cross-site request forgery (CSRF): Portswigger_labs/CSRF.md
      - Insecure deserialization: Portswigger_labs/Insecure_deserialization
      - NoSQL injection: Portswigger_labs/NoSQL_Inj.md
      - Server-side template injection: Portswigger_labs/SS_tem_Inj.md
      - SQL injection: Portswigger_labs/SQL_Inj.md
      - Server-side request forgery (SSRF): Portswigger_labs/ssrf.md
  - Try Hack Me Rooms:
      - Brooklyn Nine Nine: Try_hack_me/brooklyn_nine_nine.md
      - Agent Sudo: Try_hack_me/Agent_sudo.md
      - Year of the Rabbit: Try_hack_me/yearofrabbit.md
      - Brute It: Try_hack_me/bruteit.md